name: awesome-deploy-jdk11

on:
  push:
    branches:
      - main
    paths:
      - "awesome-deploy-jdk11/**"
  pull_request:
    branches:
      - main
    paths:
      - "awesome-deploy-jdk11/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          context: jdk11/.
          push: true
          tags: peniakoff/awesome-deploy:jdk11-latest
