name: awesome-deploy-jdk8

on:
  push:
    branches:
      - master
    paths:
      - "awesome-deploy-jdk8/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./awesome-deploy-jdk8
          push: true
          tags: peniakoff/awesome-deploy:jdk8-latest
